name: merge_me

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events with merge-me tag
  push:
    tags:
      - "merge-me"
  pull_request:
    tags:
      - "merge-me"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  merge-me:
    name: Merge me!
    needs:
      - build
      - code-review
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` environment variable with permissions to
          # push to a protected branch must be used. This variable can have an
          # arbitrary name, as an example, this repository uses
          # `GITHUB_TOKEN_DOTTBOTT`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}